spring:
  application:
    name: football-competition-api
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fotball-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: hbstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.galero: DEBUG
    org.hibernate.SQL: INFO
    liquibase: INFO
google:
  client:
    id: 353416216408-ndooeo8gs02oqo2b7qc3k3glh6tn2gfe.apps.googleusercontent.com
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
