spring:
  application:
    name: football-competition-api
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.utmaoqhbsezhaxjpjpdp&password=31044050Rsl^
    username: postgres
    password: 31044050Rsl^
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.galero: DEBUG
    org.hibernate.SQL: INFO
    liquibase: INFO
google:
  client:
    id: 353416216408-ndooeo8gs02oqo2b7qc3k3glh6tn2gfe.apps.googleusercontent.com
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
